// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudflare.pages.outputs;

import com.pulumi.cloudflare.pages.outputs.GetDomainsResult;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetDomainsInvokeResult {
    /**
     * @return Identifier.
     * 
     */
    private String accountId;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return Max items to fetch, default: 1000
     * 
     */
    private @Nullable Integer maxItems;
    /**
     * @return Name of the project.
     * 
     */
    private String projectName;
    /**
     * @return The items returned by the data source
     * 
     */
    private List<GetDomainsResult> results;

    private GetDomainsInvokeResult() {}
    /**
     * @return Identifier.
     * 
     */
    public String accountId() {
        return this.accountId;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Max items to fetch, default: 1000
     * 
     */
    public Optional<Integer> maxItems() {
        return Optional.ofNullable(this.maxItems);
    }
    /**
     * @return Name of the project.
     * 
     */
    public String projectName() {
        return this.projectName;
    }
    /**
     * @return The items returned by the data source
     * 
     */
    public List<GetDomainsResult> results() {
        return this.results;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDomainsInvokeResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accountId;
        private String id;
        private @Nullable Integer maxItems;
        private String projectName;
        private List<GetDomainsResult> results;
        public Builder() {}
        public Builder(GetDomainsInvokeResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accountId = defaults.accountId;
    	      this.id = defaults.id;
    	      this.maxItems = defaults.maxItems;
    	      this.projectName = defaults.projectName;
    	      this.results = defaults.results;
        }

        @CustomType.Setter
        public Builder accountId(String accountId) {
            if (accountId == null) {
              throw new MissingRequiredPropertyException("GetDomainsInvokeResult", "accountId");
            }
            this.accountId = accountId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetDomainsInvokeResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder maxItems(@Nullable Integer maxItems) {

            this.maxItems = maxItems;
            return this;
        }
        @CustomType.Setter
        public Builder projectName(String projectName) {
            if (projectName == null) {
              throw new MissingRequiredPropertyException("GetDomainsInvokeResult", "projectName");
            }
            this.projectName = projectName;
            return this;
        }
        @CustomType.Setter
        public Builder results(List<GetDomainsResult> results) {
            if (results == null) {
              throw new MissingRequiredPropertyException("GetDomainsInvokeResult", "results");
            }
            this.results = results;
            return this;
        }
        public Builder results(GetDomainsResult... results) {
            return results(List.of(results));
        }
        public GetDomainsInvokeResult build() {
            final var _resultValue = new GetDomainsInvokeResult();
            _resultValue.accountId = accountId;
            _resultValue.id = id;
            _resultValue.maxItems = maxItems;
            _resultValue.projectName = projectName;
            _resultValue.results = results;
            return _resultValue;
        }
    }
}
