// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pages

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-cloudflare/sdk/v6/go/cloudflare/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-cloudflare/sdk/v6/go/cloudflare/pages"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := pages.LookupProjects(ctx, &pages.LookupProjectsArgs{
//				AccountId: "023e105f4ecef8ad9ca31a8372d0c353",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupProjects(ctx *pulumi.Context, args *LookupProjectsArgs, opts ...pulumi.InvokeOption) (*LookupProjectsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupProjectsResult
	err := ctx.Invoke("cloudflare:pages/getProjects:getProjects", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProjects.
type LookupProjectsArgs struct {
	// Identifier.
	AccountId string `pulumi:"accountId"`
	// Max items to fetch, default: 1000
	MaxItems *int `pulumi:"maxItems"`
}

// A collection of values returned by getProjects.
type LookupProjectsResult struct {
	// Identifier.
	AccountId string `pulumi:"accountId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Max items to fetch, default: 1000
	MaxItems *int `pulumi:"maxItems"`
	// The items returned by the data source
	Results []GetProjectsResult `pulumi:"results"`
}

func LookupProjectsOutput(ctx *pulumi.Context, args LookupProjectsOutputArgs, opts ...pulumi.InvokeOption) LookupProjectsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupProjectsResultOutput, error) {
			args := v.(LookupProjectsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("cloudflare:pages/getProjects:getProjects", args, LookupProjectsResultOutput{}, options).(LookupProjectsResultOutput), nil
		}).(LookupProjectsResultOutput)
}

// A collection of arguments for invoking getProjects.
type LookupProjectsOutputArgs struct {
	// Identifier.
	AccountId pulumi.StringInput `pulumi:"accountId"`
	// Max items to fetch, default: 1000
	MaxItems pulumi.IntPtrInput `pulumi:"maxItems"`
}

func (LookupProjectsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProjectsArgs)(nil)).Elem()
}

// A collection of values returned by getProjects.
type LookupProjectsResultOutput struct{ *pulumi.OutputState }

func (LookupProjectsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProjectsResult)(nil)).Elem()
}

func (o LookupProjectsResultOutput) ToLookupProjectsResultOutput() LookupProjectsResultOutput {
	return o
}

func (o LookupProjectsResultOutput) ToLookupProjectsResultOutputWithContext(ctx context.Context) LookupProjectsResultOutput {
	return o
}

// Identifier.
func (o LookupProjectsResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectsResult) string { return v.AccountId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupProjectsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Max items to fetch, default: 1000
func (o LookupProjectsResultOutput) MaxItems() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupProjectsResult) *int { return v.MaxItems }).(pulumi.IntPtrOutput)
}

// The items returned by the data source
func (o LookupProjectsResultOutput) Results() GetProjectsResultArrayOutput {
	return o.ApplyT(func(v LookupProjectsResult) []GetProjectsResult { return v.Results }).(GetProjectsResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupProjectsResultOutput{})
}
